apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hbase
spec:
  selector:
    matchLabels:
      app: hbase
  template:
    metadata:
      labels:
        app: hbase
      name: hbase
    spec:
      hostname: hbase
      volumes:
        - name: hbase-opt-data
          hostPath:
            path: /dockerdata-nfs/onapdemo/aai/hbase/opt/data
      containers:
      - name: hbase
        image: aaidocker/aai-hbase-1.2.3:latest
        volumeMounts:
        - mountPath: /opt/data/
          name: hbase-opt-data
        ports:
        - containerPort: 8020
        readinessProbe:
          tcpSocket:
            port: 8020
          initialDelaySeconds: 5
          periodSeconds: 10
