# this is a shared resource for subcharts
apiVersion: v1
kind: ConfigMap
metadata:
  name: aai-filebeat
  namespace: {{ include "common.namespace" . }}
data:
{{ tpl (.Files.Glob "resources/config/log/filebeat/*").AsConfig . | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aai-deployment-configmap
  namespace: {{ include "common.namespace" . }}
data:
{{ tpl (.Files.Glob "resources/config/haproxy/*").AsConfig . | indent 2 }}
---
# this is a shared resource for subcharts
apiVersion: v1
kind: ConfigMap
metadata:
  name: aai-chef-config
  namespace: {{ include "common.namespace" . }}
data:
{{ tpl (.Files.Glob "resources/config/aai-data/chef-config/dev/.knife/solo.rb").AsConfig . | indent 2 }}
---
# this is a shared resource for subcharts
apiVersion: v1
kind: ConfigMap
metadata:
  name: aai-resources-environments
  namespace: {{ include "common.namespace" . }}
data:
{{ tpl (.Files.Glob "resources/config/aai-data/environments/*").AsConfig . | indent 2 }}

